### ISSUE TITLE
Similiar syntax from Sublime

### ISSUE THREAD

**Issue by Ermesx** [imrichardcole/language-logstash#1]
Hi,
It could be good inspiration for you:
https://github.com/nir0s/sublime-logstash-syntax-highlighter

I've converted it using this: https://discuss.atom.io/t/convert-sublime-grammar-to-atom-grammar/14843
and looks like that with Base16 Tomorrow Dark theme:
<img width="559" alt="zrzut ekranu 2016-04-17 o 17 36 04" src="https://cloud.githubusercontent.com/assets/5731890/14588174/0bf50d56-04c3-11e6-9abc-9bdbb999d4d2.png">

Also here my logstash.cson
[logstash.cson.zip](https://github.com/imrichardcole/language-logstash/files/222714/logstash.cson.zip)

**Comment by imrichardcole** [comment]
@Ermesx thanks for that, have it pretty much wrapped up with a few other changes.  Would you mind taking it for a spin if I publish a new version please?

**Comment by Ermesx** [comment]
Can't wait :)

**Comment by imrichardcole** [comment]
available in v0.1.2 now

**Comment by Ermesx** [comment]
Works well and do the same as I described above. I close this issue because it is done but I will open new ones. :)
