### ISSUE TITLE
Missing grammar for: if "xxx" in [fieldName]  

### ISSUE THREAD

**Issue by Ermesx** [imrichardcole/language-logstash#3]
Color for if and fiieldName is missing. Example:
<img width="372" alt="zrzut ekranu 2016-04-18 o 21 51 32" src="https://cloud.githubusercontent.com/assets/5731890/14617823/13d66536-05b0-11e6-9da4-5e39e50098df.png">

**Comment by imrichardcole** [comment]
fixed in 0.1.3

**Comment by Ermesx** [comment]
Is it already published ?

**Comment by imrichardcole** [comment]
ended up wrapping up this and issue 4 in 0.1.4 which is now available.  Welcome your feedback
