### ISSUE TITLE
Missing grammar for numbers in single line

### ISSUE THREAD

**Issue by Ermesx** [imrichardcole/language-logstash#4]
When I have something like that:
<img width="210" alt="zrzut ekranu 2016-04-18 o 21 56 17" src="https://cloud.githubusercontent.com/assets/5731890/14617947/96347d56-05b0-11e6-9a37-a346943aab3d.png">
grammar works well but when I compress it to the single line the number is not recognized:
<img width="265" alt="zrzut ekranu 2016-04-18 o 21 57 26" src="https://cloud.githubusercontent.com/assets/5731890/14617953/990b310a-05b0-11e6-9034-d7d07a3aea9a.png">

It also doesn't work for filters like grok, mutate and so on.

**Comment by imrichardcole** [comment]
added in 0.1.4
