### ISSUE TITLE
if statement doesn't work when field name contains @

### ISSUE THREAD

**Issue by Ermesx** [imrichardcole/language-logstash#5]
Hi, another issue:
<img width="304" alt="zrzut ekranu 2016-04-24 o 19 07 11" src="https://cloud.githubusercontent.com/assets/5731890/14769626/c84991fe-0a5c-11e6-9bd2-fa4d70f0b86e.png">

If statement doesn't work when field name contains "@"

**Comment by imrichardcole** [comment]
ok - from the screenshot above it also looks like `else if` doesn't behave as expected either?

**Comment by Ermesx** [comment]
`else if` works fine in common cases. Only this one doesn't work correct.

**Comment by Ermesx** [comment]
Partially resolved in 0.1.6 :+1: 
![image](https://cloud.githubusercontent.com/assets/5731890/14848373/a02e72b2-0c6d-11e6-8f31-a9f335daded4.png)

**Comment by imrichardcole** [comment]
closed in 0.1.7
