### ISSUE TITLE
If statement with many bool operators 

### ISSUE THREAD

**Issue by Ermesx** [imrichardcole/language-logstash#6]
Hi issue:
<img width="959" alt="zrzut ekranu 2016-04-25 o 23 01 40" src="https://cloud.githubusercontent.com/assets/5731890/14798914/1fd3fbd4-0b3a-11e6-91f7-f53288b16cda.png">

Colors for fields disappear.

**Comment by imrichardcole** [comment]
fixed in 0.1.6 and published
